# Generated by Django 5.2.17 on 2026-10-02 18:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0005_animal_animalstay_animal_animal_sex_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(default="MILK", max_length=16)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONFIRMADA", "Confirmada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=16,
                    ),
                ),
                ("lock_version", models.PositiveIntegerField(default=1)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.location"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.product"
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADA", "Publicada"),
                            ("SUPERADA", "Superada"),
                        ],
                        default="BORRADOR",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="production.production",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="production",
            name="current_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="production.productionversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionversion",
            constraint=models.UniqueConstraint(
                fields=("production", "number"), name="production_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="production_quantity_nonnegative"
            ),
        ),
    ]
