/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cuenta propia */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        events: components["schemas"]["Command"][];
                    };
                };
            };
            responses: {
                /** @description Acuses individuales */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            results: components["schemas"]["Acknowledgement"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Role: "PRODUCCION" | "TRANSPORTE" | "RECEPCION" | "ADMIN";
        Assignment: {
            id: string;
            role: components["schemas"]["Role"];
            location_id: string | null;
            location_name: string;
            /** @enum {string} */
            scope: "GLOBAL" | "UBICACION";
        };
        Account: {
            /** Format: uuid */
            id: string;
            username: string;
            name: string;
            change_password_required: boolean;
            assignments: components["schemas"]["Assignment"][];
            capabilities: string[];
        };
        ErrorBody: {
            code: string;
            message: string;
            retryable: boolean;
            field_errors?: {
                [key: string]: string[];
            };
        };
        /** @enum {string} */
        CommandType: "MILKING_CREATE" | "MILKING_UPDATE" | "MILKING_CONFIRM" | "MILKING_RECTIFY" | "MILKING_VOID" | "TRANSFER_CREATE" | "TRANSFER_UPDATE" | "TRANSFER_SEND" | "TRANSFER_REVISE" | "TRANSFER_CANCEL" | "TRANSFER_PICKUP" | "TRANSFER_RECEIVE" | "CORRECTION_CREATE" | "CORRECTION_ACCEPT" | "CORRECTION_REJECT" | "CORRECTION_WITHDRAW";
        Command: {
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            device_id: string;
            type: components["schemas"]["CommandType"];
            /** Format: uuid */
            entity_id: string;
            /** Format: date-time */
            occurred_at: string;
            expected_version?: number;
            depends_on: string[];
            payload: {
                [key: string]: unknown;
            };
        };
        Acknowledgement: {
            /** Format: uuid */
            event_id: string;
            /** @enum {string} */
            status: "RECIBIDA" | "ESPERA_DEPENDENCIA" | "APLICADA" | "RECHAZADA";
            /** Format: uuid */
            entity_id: string;
            lock_version?: number;
            result?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            server_received_at: string;
            error?: components["schemas"]["ErrorBody"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
