# Generated by Django 5.2.17 on 2026-10-02 18:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0005_animal_animalstay_animal_animal_sex_valid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilkingDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("liters", models.DecimalField(decimal_places=3, max_digits=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Milking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField()),
                ("voided_at", models.DateTimeField(null=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.location"
                    ),
                ),
            ],
        ),
    ]
