# Generated by Django 5.2.17 on 2026-10-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0005_animal_animalstay_animal_animal_sex_valid_and_more"),
        ("milk", "0001_initial"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="milking",
            name="production",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="milking",
                to="production.production",
            ),
        ),
        migrations.AddField(
            model_name="milking",
            name="replaces",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replacements",
                to="milk.milking",
            ),
        ),
        migrations.AddField(
            model_name="milking",
            name="turn",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="catalog.turn"),
        ),
        migrations.AddField(
            model_name="milkingdetail",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.animal"
            ),
        ),
        migrations.AddField(
            model_name="milkingdetail",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="details",
                to="production.productionversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="milkingdetail",
            constraint=models.UniqueConstraint(
                fields=("version", "animal"), name="milking_version_animal_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="milkingdetail",
            constraint=models.CheckConstraint(
                condition=models.Q(("liters__isnull", True), ("liters__gte", 0), _connector="OR"),
                name="milking_liters_nonnegative",
            ),
        ),
    ]
