# Generated by Django 5.2.17 on 2026-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_animal_animalstay_animal_animal_sex_valid_and_more"),
        ("milk", "0002_initial"),
        ("production", "0002_published_immutable"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="milking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("voided_at__isnull", True)),
                fields=("center", "date", "turn"),
                name="milking_active_center_date_turn_unique",
            ),
        ),
    ]
