# Generated by Django 5.2.17 on 2026-10-02 18:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("production", "0002_published_immutable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=48, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "production",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lot",
                        to="production.production",
                    ),
                ),
            ],
        ),
    ]
