# Generated by Django 5.2.17 on 2026-10-02 18:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_animal_animalstay_animal_animal_sex_valid_and_more"),
        ("sync", "0001_initial"),
        ("traceability", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=48, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PENDIENTE_RECOGIDA", "Pendiente Recogida"),
                            ("EN_CAMINO", "En Camino"),
                            ("RECIBIDO", "Recibido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        max_length=24,
                    ),
                ),
                ("lock_version", models.PositiveIntegerField(default=1)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "BORRADOR"),
                            ("PROPUESTA", "PROPUESTA"),
                            ("PUBLICADA", "PUBLICADA"),
                            ("SUPERADA", "SUPERADA"),
                            ("RETIRADA", "RETIRADA"),
                        ],
                        default="BORRADOR",
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.location",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.location",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="traceability.transfer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransferLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("units", models.DecimalField(decimal_places=3, max_digits=14)),
                ("content_base_snapshot", models.DecimalField(decimal_places=3, max_digits=14)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="traceability.lot"
                    ),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.presentation"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="traceability.transferversion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transfer",
            name="current_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="traceability.transferversion",
            ),
        ),
        migrations.CreateModel(
            name="Conformity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("ENTREGA_ORIGEN", "ENTREGA_ORIGEN"),
                            ("RECOGIDA", "RECOGIDA"),
                            ("RECEPCION", "RECEPCION"),
                        ],
                        max_length=24,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sync.syncoperation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conformities",
                        to="traceability.transferversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConformityDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("accepted_quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "conformity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="details",
                        to="traceability.conformity",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="traceability.transferline"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conformity", "line"), name="conformity_detail_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transferversion",
            constraint=models.UniqueConstraint(
                fields=("transfer", "number"), name="transfer_version_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="transferline",
            constraint=models.UniqueConstraint(
                fields=("version", "lot", "presentation"), name="transfer_line_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="transferline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("content_base_snapshot__gt", 0), ("quantity__gt", 0), ("units__gt", 0)
                ),
                name="transfer_line_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="conformity",
            constraint=models.UniqueConstraint(
                fields=("version", "stage"), name="version_conformity_stage_unique"
            ),
        ),
    ]
