# Generated by Django 5.2.17 on 2026-10-02 19:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traceability", "0004_conformity_immutable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Correction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "PENDIENTE"),
                            ("APLICADA", "APLICADA"),
                            ("RECHAZADA", "RECHAZADA"),
                            ("RETIRADA", "RETIRADA"),
                        ],
                        default="PENDIENTE",
                        max_length=16,
                    ),
                ),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "original_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="traceability.transferversion",
                    ),
                ),
                (
                    "proposed_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="traceability.transferversion",
                    ),
                ),
                (
                    "reception_approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corrections",
                        to="traceability.transfer",
                    ),
                ),
                (
                    "transport_approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "PENDIENTE")),
                        fields=("transfer",),
                        name="one_pending_correction",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("transport_approver", models.F("reception_approver")), _negated=True
                        ),
                        name="correction_distinct_approvers",
                    ),
                ],
            },
        ),
    ]
