# Generated by Django 5.2.17 on 2026-10-02 19:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
        ("traceability", "0006_correction_fixed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrectionDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[("TRANSPORTE", "TRANSPORTE"), ("RECEPCION", "RECEPCION")],
                        max_length=16,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("ACEPTAR", "ACEPTAR"), ("RECHAZAR", "RECHAZAR")], max_length=16
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField()),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "correction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="traceability.correction",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sync.syncoperation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("correction", "function"), name="one_decision_per_function"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("decision", "RECHAZAR"), _negated=True),
                            models.Q(("reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="rejection_requires_reason",
                    ),
                ],
            },
        ),
    ]
