# Generated by Django 5.2.17 on 2026-10-02 14:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("prepared_at", models.DateTimeField(null=True)),
                ("preparation_expires_at", models.DateTimeField(null=True)),
                ("last_contact_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                ("event_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=40)),
                ("entity_id", models.UUIDField()),
                ("expected_version", models.PositiveIntegerField(null=True)),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECIBIDA", "Recibida"),
                            ("ESPERA_DEPENDENCIA", "Espera Dependencia"),
                            ("APLICADA", "Aplicada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="RECIBIDA",
                        max_length=24,
                    ),
                ),
                ("response", models.JSONField(default=dict)),
                ("http_status", models.PositiveSmallIntegerField(default=200)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sync.device"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("depends_on_event_id", models.UUIDField()),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependencies",
                        to="sync.syncoperation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="syncoperation",
            index=models.Index(fields=["user", "state"], name="sync_syncop_user_id_7a2262_idx"),
        ),
        migrations.AddConstraint(
            model_name="syncdependency",
            constraint=models.UniqueConstraint(
                fields=("operation", "depends_on_event_id"), name="operation_dependency_unique"
            ),
        ),
    ]
