# Generated by Django 5.2.17 on 2026-10-02 13:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[("CENTRO", "Centro"), ("PUNTO_VENTA", "Punto Venta")],
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["CENTRO", "PUNTO_VENTA"])),
                        name="location_kind_valid",
                    )
                ],
            },
        ),
    ]
