# Generated by Django 5.2.17 on 2026-10-02 14:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "code",
                    models.CharField(
                        choices=[("L", "L"), ("KG", "KG"), ("UN", "UN")],
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("code__in", ["L", "KG", "UN"])), name="unit_code_valid"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("active", models.BooleanField(default=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.unit"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CenterProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.location"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.product"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("center", "product"), name="center_product_unique"
                    )
                ],
            },
        ),
    ]
