import uuid

# Generated by Django 5.2.17 on 2026-10-02 18:20
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_species_turn_presentation"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("HEMBRA", "Hembra"), ("MACHO", "Macho")], max_length=8
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=8,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.species"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnimalStay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stays",
                        to="catalog.animal",
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.location"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                condition=models.Q(("sex__in", ["HEMBRA", "MACHO"])), name="animal_sex_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="animal",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVO", "INACTIVO"])),
                name="animal_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="animalstay",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_on__isnull", True),
                    ("ends_on__gt", models.F("starts_on")),
                    _connector="OR",
                ),
                name="animal_stay_period_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="animalstay",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("animal", "="),
                    (
                        models.Func(
                            "starts_on",
                            "ends_on",
                            models.Value("[)"),
                            function="DATERANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="animal_stays_no_overlap",
            ),
        ),
    ]
