# Generated by Django 5.2.17 on 2026-10-02 19:06

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("source_event_id", models.UUIDField()),
                ("entity_type", models.CharField(max_length=32)),
                ("entity_id", models.UUIDField()),
                ("version_id", models.UUIDField(null=True)),
                ("title", models.CharField(max_length=160)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at", "-id"],
                        name="notificatio_recipie_e86c4c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "source_event_id", "type"),
                        name="notification_event_recipient_unique",
                    )
                ],
            },
        ),
    ]
