# Generated by Django 5.2.17 on 2026-10-02 20:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "PENDIENTE"),
                            ("PROCESANDO", "PROCESANDO"),
                            ("ACEPTADO_PROVEEDOR", "ACEPTADO_PROVEEDOR"),
                            ("REINTENTABLE", "REINTENTABLE"),
                            ("FALLIDO", "FALLIDO"),
                            ("DESCARTADO", "DESCARTADO"),
                        ],
                        default="PENDIENTE",
                        max_length=24,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_until", models.DateTimeField(null=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("last_error", models.CharField(blank=True, max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="notifications.pushsubscription",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "next_attempt_at"], name="notificatio_state_e680d6_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "subscription"),
                        name="one_push_per_subscription_event",
                    )
                ],
            },
        ),
    ]
