# Generated by Django 5.2.17 on 2026-10-02 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_pushdelivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("seen_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
